site_name: releases-dashboard
repo_url: https://github.com:rock-hu/releases-dashboard
repo_name: rock-hu/releases-dashboard
site_dir: public
theme:
  name: material
  include_search_page: false
  search_index_only: true
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - java
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
nav:
  - mkdocs.md
  - airbnb:
      - airbnb/lottie-android/README.md
      - airbnb/lottie-ios/README.md
      - airbnb/Showkase/README.md
      - airbnb/swift/README.md
  - android:
      - android/compose-samples/README.md
  - apache:
      - apache/camel/README.md
  - argo:
      - argoproj/argo-cd-ui/README.md
      - argoproj/argo-cd/README.md
      - argoproj/argo-ci/README.md
      - argoproj/argo-events/README.md
      - argoproj/argo-helm/README.md
      - argoproj/argo-rollouts/README.md
      - argoproj/argo-ui/README.md
      - argoproj/argo-workflows/README.md
      - argoproj/argoproj-deployments/README.md
      - argoproj/gitops-engine/README.md
      - argoproj/kubeflow-ks/README.md
      - argoproj/sdk-java/README.md
  - backstage:
      - backstage/backstage/README.md
  - callstack:
      - callstack/react-native-builder-bob/README.md
      - callstack/react-native-paper/README.md
      - callstack/repack/README.md
  - ConsumerDataStandardsAustralia:
      - ConsumerDataStandardsAustralia/ADR-Gateway/README.md
      - ConsumerDataStandardsAustralia/infosec/README.md
      - ConsumerDataStandardsAustralia/register/README.md
      - ConsumerDataStandardsAustralia/standards/README.md
  - Decathlon:
      - Decathlon/vitamin-compose/README.md
      - Decathlon/vitamin-design/README.md
      - Decathlon/vitamin-ios/README.md
      - Decathlon/vitamin-web/README.md
  - facebook:
      - facebook/litho/README.md
      - facebook/metro/README.md
      - facebook/react-native/README.md
      - facebook/react/README.md
  - FasterXML:
      - FasterXML/jackson-datatype-joda/README.md
      - FasterXML/jackson-datatype-json-org/README.md
      - FasterXML/jackson-datatype-jsr310/README.md
      - FasterXML/jackson-datatype-jsr353/README.md
      - FasterXML/jackson-datatypes-collections/README.md
      - FasterXML/jackson-datatypes-misc/README.md
      - FasterXML/jackson-jaxrs-providers/README.md
      - FasterXML/jackson-jdk11-compat-test/README.md
      - FasterXML/jackson-jdk17-compat-test/README.md
      - FasterXML/jackson-jdk6-compat-test/README.md
      - FasterXML/jackson-jr/README.md
      - FasterXML/jackson-module-afterburner/README.md
      - FasterXML/jackson-module-guice/README.md
      - FasterXML/jackson-module-jaxb-annotations/README.md
      - FasterXML/jackson-module-mrbean/README.md
      - FasterXML/jackson-module-osgi/README.md
      - FasterXML/jackson-module-parameter-names/README.md
      - FasterXML/jackson-module-paranamer/README.md
      - FasterXML/jackson-modules-base/README.md
      - FasterXML/jackson-modules-java8/README.md
  - ff4j/ff4j/README.md
  - kubernetes:
      - istio/istio/README.md
      - kubernetes/kubernetes/README.md

  - netty/netty/README.md
  - telemetry:
      - open-telemetry/opentelemetry-collector/README.md
      - open-telemetry/opentelemetry-java-instrumentation/README.md
      - open-telemetry/opentelemetry-java/README.md
      - micrometer-metrics/micrometer/README.md
  - OpenBanking-Brasil:
      - OpenBanking-Brasil/openapi/README.md
      - OpenBanking-Brasil/pcm-openapi/README.md
      - OpenBanking-Brasil/ressarcimento/README.md
      - OpenBanking-Brasil/specs-directory/README.md
      - OpenBanking-Brasil/specs-pcm/README.md
      - OpenBanking-Brasil/specs-seguranca-pp/README.md
      - OpenBanking-Brasil/specs-seguranca/README.md
      - OpenBanking-Brasil/specs-servicedesk/README.md
      - OpenBanking-Brasil/specs-weekly-details/README.md
  - OpenBankingUK:
      - OpenBankingUK/read-write-api-specs/README.md
  - openfaas:
      - openfaas/cloud-functions/README.md
      - openfaas/faas-cli/README.md
      - openfaas/faas-middleware/README.md
      - openfaas/faas-netes/README.md
      - openfaas/faas-provider/README.md
      - openfaas/faas-swarm/README.md
      - openfaas/faasd/README.md
      - openfaas/ingress-operator/README.md
      - openfaas/mqtt-connector/README.md
      - openfaas/nats-connector/README.md
      - openfaas/nats-queue-worker/README.md
      - openfaas/of-watchdog/README.md
      - openfaas/openfaas-cloud/README.md
      - openfaas/store-functions/README.md
      - openfaas/store/README.md
  - openrewrite:
      - openrewrite/rewrite-recipe-bom/README.md
      - openrewrite/rewrite/README.md
  - prowide:
      - prowide/prowide-core/README.md
      - prowide/prowide-iso20022/README.md
  - qos-ch/logback/README.md
  - react-navigation/react-navigation/README.md
  - ReactiveX/RxJava/README.md
  - resilience4j/resilience4j/README.md
  - spring-cloud:
      - spring-cloud/spring-cloud-build/README.md
      - spring-cloud/spring-cloud-bus/README.md
      - spring-cloud/spring-cloud-cli/README.md
      - spring-cloud/spring-cloud-cloudfoundry/README.md
      - spring-cloud/spring-cloud-commons/README.md
      - spring-cloud/spring-cloud-config/README.md
      - spring-cloud/spring-cloud-connectors/README.md
      - spring-cloud/spring-cloud-consul/README.md
      - spring-cloud/spring-cloud-contract/README.md
      - spring-cloud/spring-cloud-dataflow-apps-plugin/README.md
      - spring-cloud/spring-cloud-dataflow-build/README.md
      - spring-cloud/spring-cloud-dataflow-common/README.md
      - spring-cloud/spring-cloud-dataflow-ui/README.md
      - spring-cloud/spring-cloud-dataflow/README.md
      - spring-cloud/spring-cloud-deployer-cloudfoundry/README.md
      - spring-cloud/spring-cloud-deployer-kubernetes/README.md
      - spring-cloud/spring-cloud-deployer-local/README.md
      - spring-cloud/spring-cloud-deployer/README.md
      - spring-cloud/spring-cloud-function/README.md
      - spring-cloud/spring-cloud-gateway/README.md
      - spring-cloud/spring-cloud-kubernetes/README.md
      - spring-cloud/spring-cloud-netflix/README.md
      - spring-cloud/spring-cloud-open-service-broker/README.md
      - spring-cloud/spring-cloud-openfeign/README.md
      - spring-cloud/spring-cloud-release-tools/README.md
      - spring-cloud/spring-cloud-release/README.md
      - spring-cloud/spring-cloud-schema-registry/README.md
      - spring-cloud/spring-cloud-skipper/README.md
      - spring-cloud/spring-cloud-sleuth/README.md
      - spring-cloud/spring-cloud-static/README.md
      - spring-cloud/spring-cloud-stream-binder-aws-kinesis/README.md
      - spring-cloud/spring-cloud-stream-binder-kafka/README.md
      - spring-cloud/spring-cloud-stream-binder-rabbit/README.md
      - spring-cloud/spring-cloud-stream-jenkins-jobs/README.md
      - spring-cloud/spring-cloud-stream-starters/README.md
      - spring-cloud/spring-cloud-stream/README.md
      - spring-cloud/spring-cloud-task/README.md
      - spring-cloud/spring-cloud-vault/README.md
      - spring-cloud/spring-cloud-zookeeper/README.md
      - spring-cloud/spring-functions-catalog/README.md
      - spring-cloud/stream-applications/README.md
  - spring-projects:
      - spring-projects/spring-ai/README.md
      - spring-projects/spring-amqp/README.md
      - spring-projects/spring-batch/README.md
      - spring-projects/spring-boot/README.md
      - spring-projects/spring-framework/README.md
      - spring-projects/spring-guice/README.md
      - spring-projects/spring-hateoas/README.md
      - spring-projects/spring-integration-aws/README.md
      - spring-projects/spring-integration-extensions/README.md
      - spring-projects/spring-integration-flow/README.md
      - spring-projects/spring-integration-splunk/README.md
      - spring-projects/spring-integration/README.md
      - spring-projects/spring-kafka/README.md
      - spring-projects/spring-ldap/README.md
      - spring-projects/spring-modulith/README.md
      - spring-projects/spring-plugin/README.md
      - spring-projects/spring-pulsar/README.md
      - spring-projects/spring-restdocs/README.md
      - spring-projects/spring-retry/README.md
      - spring-projects/spring-security-kerberos/README.md
      - spring-projects/spring-security/README.md
      - spring-projects/spring-session-bom/README.md
      - spring-projects/spring-session-data-geode/README.md
      - spring-projects/spring-session-data-mongodb/README.md
      - spring-projects/spring-session/README.md
      - spring-projects/spring-statemachine/README.md
      - spring-projects/spring-vault/README.md
      - spring-projects/spring-webflow/README.md
      - spring-projects/spring-ws/README.md
  - square/okhttp/README.md
  - stoplightio:
      - stoplightio/elements/README.md
      - stoplightio/prism/README.md
      - stoplightio/spectral-action/README.md
      - stoplightio/spectral-owasp-ruleset/README.md
      - stoplightio/spectral-url-versioning/README.md
      - stoplightio/spectral/README.md
      - stoplightio/stoplight-cli-workflow/README.md
      - stoplightio/vscode-spectral/README.md
  - swagger-api:
      - swagger-api/swagger-codegen-generators/README.md
      - swagger-api/swagger-codegen/README.md
      - swagger-api/swagger-inflector/README.md
      - swagger-api/swagger-parser/README.md
      - swagger-api/validator-badge/README.md
  - testcontainers/testcontainers-java/README.md
  - twitter/compose-rules/README.md
  - uber/RIBs/README.md
  - wix:
      - wix/react-native-navigation/README.md
      - wix/react-native-notifications/README.md
      - wix/react-native-ui-lib/README.md
  - zalando:
      - zalando/faux-pas/README.md
      - zalando/jackson-datatype-money/README.md
      - zalando/logbook/README.md
      - zalando/opentracing-toolbox/README.md
      - zalando/patroni/README.md
      - zalando/PGObserver/README.md
      - zalando/postgres-operator/README.md
      - zalando/problem-spring-web/README.md
      - zalando/problem/README.md
      - zalando/public-presentations/README.md
      - zalando/riptide/README.md
      - zalando/skipper/README.md
      - zalando/spilo/README.md
      - zalando/spring-cloud-config-aws-kms/README.md
      - zalando/tailor/README.md
      - zalando/tech-radar/README.md
      - zalando/zalenium/README.md
      - zalando/zally/README.md
      - zalando/zappr/README.md
      - zalando/zmon/README.md

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - git-authors
  - git-revision-date-localized:
      type: date
  - table-reader
extra:
  version:
    method: mike
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - admonition
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
